config/routes.rb
Rails.application.routes.draw do
  get 'site/increment', as: :increment
  root "site#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def increment
    @counter = (params[:counter]&.to_i || 0) + 1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
  def rand_color
    "%06x" % (rand * 0xffffff)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newproj</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="container mt-8 mx-auto">
    <%= yield %>
    </div>
  </body>
</html>

app/views/site/increment.html.erb
<turbo-frame id="counter">
  <div class="mt-4" style="color: #<%=rand_color%>;">Current count:<%= @counter %></div>
  <div class="mt-4"><%= link_to "Increment", increment_path(counter: @counter), class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>Increment</div>
</turbo-frame>

app/views/site/index.html.erb
<h1 class="text-3xl font-bold underline">
    Hello world!
</h1>

<%= turbo_frame_tag "counter", src: increment_path %>